package com.costcook.service.impl;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.costcook.entity.Category;
import com.costcook.entity.Ingredient;
import com.costcook.entity.Unit;
import com.costcook.repository.CategoryRepository;
import com.costcook.repository.IngredientRepository;
import com.costcook.repository.UnitRepository;
import com.costcook.service.IngredientService;

import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public class IngredientServiceImpl implements IngredientService {
	
	private final IngredientRepository ingredientRepository;
	private final CategoryRepository categoryRepository;
	private final UnitRepository unitRepository;
	
	// 카테고리, 양 객체의 ID만 찾기
	private Category findCategoryById(Long id) {
		return categoryRepository.findById(id).orElse(null);
	}
	private Unit findUnitById(Long id) {
		return unitRepository.findById(id).orElse(null);
	}

	@Override
	@Transactional
	public void insertIngredients() {
		Ingredient[] ingredients = {
				new Ingredient(1L, "간장", findCategoryById(10L), findUnitById(1L), 48),
				new Ingredient(2L, "감자", findCategoryById(1L), findUnitById(5L), 330),
				new Ingredient(3L, "계란", findCategoryById(12L), findUnitById(5L), 133),
				new Ingredient(4L, "고추기름", findCategoryById(10L), findUnitById(1L), 92),
				new Ingredient(5L, "고추장", findCategoryById(10L), findUnitById(1L), 265),
				new Ingredient(6L, "국간장", findCategoryById(10L), findUnitById(1L), 137),
				new Ingredient(7L, "꽈리고추", findCategoryById(1L), findUnitById(3L), 13),
				new Ingredient(8L, "녹말가루", findCategoryById(4L), findUnitById(1L), 64),
				new Ingredient(9L, "다진마늘", findCategoryById(10L), findUnitById(1L), 138),
				new Ingredient(10L, "단호박", findCategoryById(1L), findUnitById(3L), 7),
				new Ingredient(11L, "달걀", findCategoryById(12L), findUnitById(5L), 116),
				new Ingredient(12L, "닭가슴살", findCategoryById(3L), findUnitById(3L), 12),
				new Ingredient(13L, "당근", findCategoryById(1L), findUnitById(5L), 1260),
				new Ingredient(14L, "대파", findCategoryById(1L), findUnitById(6L), 456),
				new Ingredient(15L, "두부", findCategoryById(6L), findUnitById(7L), 3708),
				new Ingredient(16L, "딸기잼", findCategoryById(9L), findUnitById(3L), 12),
				new Ingredient(17L, "마늘", findCategoryById(1L), findUnitById(8L), 60),
				new Ingredient(18L, "마요네즈", findCategoryById(10L), findUnitById(1L), 633),
				new Ingredient(19L, "맛술", findCategoryById(10L), findUnitById(1L), 5),
				new Ingredient(20L, "멸치", findCategoryById(5L), findUnitById(9L), 37),
				new Ingredient(21L, "문어", findCategoryById(8L), findUnitById(3L), 34),
				new Ingredient(22L, "물", findCategoryById(10L), findUnitById(4L), 0),
				new Ingredient(23L, "밀가루", findCategoryById(4L), findUnitById(1L), 22),
				new Ingredient(24L, "바질", findCategoryById(1L), findUnitById(3L), 59),
				new Ingredient(25L, "박력분", findCategoryById(4L), findUnitById(3L), 1),
				new Ingredient(26L, "밥", findCategoryById(2L), findUnitById(10L), 766),
				new Ingredient(27L, "버터", findCategoryById(12L), findUnitById(3L), 24),
				new Ingredient(28L, "베이킹소다", findCategoryById(10L), findUnitById(1L), 56),
				new Ingredient(29L, "베이킹파우더", findCategoryById(10L), findUnitById(1L), 117),
				new Ingredient(30L, "부침가루", findCategoryById(4L), findUnitById(11L), 798),
				new Ingredient(31L, "분유", findCategoryById(12L), findUnitById(3L), 26),
				new Ingredient(32L, "빵", findCategoryById(9L), findUnitById(5L), 76),
				new Ingredient(33L, "생강가루", findCategoryById(10L), findUnitById(3L), 13),
				new Ingredient(34L, "설탕", findCategoryById(10L), findUnitById(3L), 5),
				new Ingredient(35L, "소금", findCategoryById(10L), findUnitById(1L), 99),
				new Ingredient(36L, "스파게티면", findCategoryById(4L), findUnitById(3L), 5),
				new Ingredient(37L, "시나몬가루", findCategoryById(10L), findUnitById(3L), 2),
				new Ingredient(38L, "식빵", findCategoryById(9L), findUnitById(12L), 86),
				new Ingredient(39L, "식용유", findCategoryById(10L), findUnitById(11L), 722),
				new Ingredient(40L, "쌀뜨물", findCategoryById(2L), findUnitById(11L), 0),
				new Ingredient(41L, "양파", findCategoryById(1L), findUnitById(5L), 540),
				new Ingredient(42L, "연유", findCategoryById(12L), findUnitById(1L), 83),
				new Ingredient(43L, "옥수수통조림", findCategoryById(9L), findUnitById(13L), 591),
				new Ingredient(44L, "올리고당", findCategoryById(10L), findUnitById(1L), 277),
				new Ingredient(45L, "올리브유", findCategoryById(10L), findUnitById(1L), 540),
				new Ingredient(46L, "우유", findCategoryById(12L), findUnitById(3L), 4),
				new Ingredient(47L, "육수", findCategoryById(10L), findUnitById(11L), 0),
				new Ingredient(48L, "진간장", findCategoryById(10L), findUnitById(1L), 48),
				new Ingredient(49L, "참치", findCategoryById(8L), findUnitById(13L), 268),
				new Ingredient(50L, "참치액", findCategoryById(10L), findUnitById(1L), 15),
				new Ingredient(51L, "찹쌀가루", findCategoryById(2L), findUnitById(3L), 7),
				new Ingredient(52L, "채소", findCategoryById(1L), findUnitById(1L), 179),
				new Ingredient(53L, "청양고추", findCategoryById(1L), findUnitById(5L), 238),
				new Ingredient(54L, "청주", findCategoryById(10L), findUnitById(1L), 92),
				new Ingredient(55L, "카놀라유", findCategoryById(10L), findUnitById(1L), 193),
				new Ingredient(56L, "카레가루", findCategoryById(10L), findUnitById(1L), 34),
				new Ingredient(57L, "크랜베리", findCategoryById(13L), findUnitById(9L), 1152),
				new Ingredient(58L, "통깨", findCategoryById(6L), findUnitById(3L), 28),
				new Ingredient(59L, "파슬리가루", findCategoryById(1L), findUnitById(1L), 195),
				new Ingredient(60L, "파프리카", findCategoryById(1L), findUnitById(5L), 841),
				new Ingredient(61L, "팽이버섯", findCategoryById(1L), findUnitById(14L), 1000),
				new Ingredient(62L, "표고버섯", findCategoryById(1L), findUnitById(5L), 396),
				new Ingredient(63L, "피망", findCategoryById(1L), findUnitById(5L), 1188),
				new Ingredient(64L, "피자치즈", findCategoryById(12L), findUnitById(11L), 222),
				new Ingredient(65L, "햄", findCategoryById(9L), findUnitById(15L), 36),
				new Ingredient(66L, "후추", findCategoryById(10L), findUnitById(3L), 7),
				new Ingredient(67L, "계란노른자", findCategoryById(12L), findUnitById(5L), 133),
				new Ingredient(68L, "고추", findCategoryById(1L), findUnitById(5L), 119),
				new Ingredient(69L, "계란흰자", findCategoryById(12L), findUnitById(5L), 133),
				new Ingredient(70L, "고춧가루", findCategoryById(10L), findUnitById(1L), 940),
				new Ingredient(71L, "과일", findCategoryById(13L), findUnitById(5L), 636),
				new Ingredient(72L, "굴", findCategoryById(8L), findUnitById(5L), 170),
				new Ingredient(73L, "굴소스", findCategoryById(10L), findUnitById(1L), 168),
				new Ingredient(74L, "귤", findCategoryById(13L), findUnitById(3L), 3),
				new Ingredient(75L, "김치", findCategoryById(9L), findUnitById(16L), 11370),
				new Ingredient(76L, "김치국물", findCategoryById(9L), findUnitById(11L), 0),
				new Ingredient(77L, "깨", findCategoryById(6L), findUnitById(3L), 76),
				new Ingredient(78L, "깻잎", findCategoryById(1L), findUnitById(18L), 21),
				new Ingredient(79L, "꼬막", findCategoryById(8L), findUnitById(17L), 3160),
				new Ingredient(80L, "꽁치", findCategoryById(8L), findUnitById(13L), 7200),
				new Ingredient(81L, "상추", findCategoryById(1L), findUnitById(18L), 203),
				new Ingredient(82L, "나빠주", findCategoryById(1L), findUnitById(1L), 120),
				new Ingredient(83L, "냉동딸기", findCategoryById(13L), findUnitById(11L), 774),
				new Ingredient(84L, "다시마", findCategoryById(5L), findUnitById(18L), 261),
				new Ingredient(85L, "꿀", findCategoryById(10L), findUnitById(1L), 325),
				new Ingredient(86L, "다시다", findCategoryById(10L), findUnitById(1L), 287),
				new Ingredient(87L, "다진생강", findCategoryById(10L), findUnitById(1L), 265),
				new Ingredient(88L, "다진양파", findCategoryById(10L), findUnitById(5L), 432),
				new Ingredient(89L, "당면", findCategoryById(4L), findUnitById(9L), 745),
				new Ingredient(90L, "돼지고기", findCategoryById(11L), findUnitById(3L), 30),
				new Ingredient(91L, "된장", findCategoryById(10L), findUnitById(1L), 61),
				new Ingredient(92L, "두반장", findCategoryById(10L), findUnitById(1L), 233),
				new Ingredient(93L, "드레싱", findCategoryById(10L), findUnitById(14L), 1035),
				new Ingredient(94L, "들기름", findCategoryById(10L), findUnitById(1L), 76),
				new Ingredient(95L, "딸기", findCategoryById(13L), findUnitById(5L), 123),
				new Ingredient(96L, "땅콩", findCategoryById(6L), findUnitById(3L), 0),
				new Ingredient(97L, "떡볶이떡", findCategoryById(9L), findUnitById(3L), 8),
				new Ingredient(98L, "또띠아", findCategoryById(9L), findUnitById(18L), 594),
				new Ingredient(99L, "라면사리", findCategoryById(9L), findUnitById(17L), 558),
				new Ingredient(100L, "레몬즙", findCategoryById(10L), findUnitById(1L), 744),
				new Ingredient(101L, "만두피", findCategoryById(4L), findUnitById(18L), 39),
				new Ingredient(102L, "맛소금", findCategoryById(10L), findUnitById(3L), 5),
				new Ingredient(103L, "맛간장", findCategoryById(10L), findUnitById(11L), 830),
				new Ingredient(104L, "머스터드", findCategoryById(10L), findUnitById(1L), 172),
				new Ingredient(105L, "멸치육수", findCategoryById(5L), findUnitById(1L), 0),
				new Ingredient(106L, "명란", findCategoryById(8L), findUnitById(5L), 209),
				new Ingredient(107L, "모닝빵", findCategoryById(9L), findUnitById(5L), 245),
				new Ingredient(108L, "모짜렐라치즈", findCategoryById(12L), findUnitById(3L), 3),
				new Ingredient(109L, "물엿", findCategoryById(10L), findUnitById(1L), 28),
				new Ingredient(110L, "바나나", findCategoryById(13L), findUnitById(5L), 816),
				new Ingredient(111L, "바닐라오일", findCategoryById(10L), findUnitById(3L), 11),
				new Ingredient(112L, "바베큐소스", findCategoryById(10L), findUnitById(1L), 96),
				new Ingredient(113L, "쌀가루", findCategoryById(2L), findUnitById(3L), 5),
				new Ingredient(114L, "발사믹식초", findCategoryById(10L), findUnitById(1L), 24),
				new Ingredient(115L, "방울토마토", findCategoryById(1L), findUnitById(3L), 9),
				new Ingredient(116L, "베이컨", findCategoryById(9L), findUnitById(14L), 366),
				new Ingredient(117L, "부추", findCategoryById(1L), findUnitById(9L), 561),
				new Ingredient(118L, "브로콜리", findCategoryById(1L), findUnitById(5L), 3790),
				new Ingredient(119L, "빵가루", findCategoryById(4L), findUnitById(11L), 1154),
				new Ingredient(120L, "사과", findCategoryById(13L), findUnitById(3L), 7),
				new Ingredient(121L, "삶은계란", findCategoryById(12L), findUnitById(5L), 248),
				new Ingredient(122L, "새송이버섯", findCategoryById(1L), findUnitById(5L), 460),
				new Ingredient(123L, "새우", findCategoryById(8L), findUnitById(19L), 971),
				new Ingredient(124L, "새우살", findCategoryById(8L), findUnitById(3L), 24),
				new Ingredient(125L, "샐러드채소", findCategoryById(1L), findUnitById(14L), 4496),
				new Ingredient(126L, "생크림", findCategoryById(12L), findUnitById(11L), 206),
				new Ingredient(127L, "소고기", findCategoryById(11L), findUnitById(3L), 21),
				new Ingredient(128L, "슈가파우더", findCategoryById(10L), findUnitById(1L), 6),
				new Ingredient(129L, "스테이크소스", findCategoryById(10L), findUnitById(1L), 80),
				new Ingredient(130L, "스팸햄", findCategoryById(9L), findUnitById(13L), 148),
				new Ingredient(131L, "시럽", findCategoryById(10L), findUnitById(1L), 112),
				new Ingredient(132L, "시치미", findCategoryById(10L), findUnitById(1L), 16),
				new Ingredient(133L, "식초", findCategoryById(10L), findUnitById(1L), 6),
				new Ingredient(134L, "쌈장", findCategoryById(10L), findUnitById(1L), 136),
				new Ingredient(135L, "아몬드", findCategoryById(6L), findUnitById(3L), 1),
				new Ingredient(136L, "아몬드가루", findCategoryById(6L), findUnitById(3L), 1),
				new Ingredient(137L, "애호박", findCategoryById(1L), findUnitById(5L), 1498),
				new Ingredient(138L, "양배추", findCategoryById(1L), findUnitById(20L), 6270),
				new Ingredient(139L, "양상추", findCategoryById(1L), findUnitById(18L), 378),
				new Ingredient(140L, "어묵", findCategoryById(9L), findUnitById(18L), 20),
				new Ingredient(141L, "연근", findCategoryById(1L), findUnitById(3L), 9),
				new Ingredient(142L, "오렌지쥬스", findCategoryById(9L), findUnitById(1L), 66),
				new Ingredient(143L, "오이", findCategoryById(1L), findUnitById(5L), 698),
				new Ingredient(144L, "오징어", findCategoryById(8L), findUnitById(19L), 13174),
				new Ingredient(145L, "오징어링", findCategoryById(9L), findUnitById(3L), 13),
				new Ingredient(146L, "와인", findCategoryById(10L), findUnitById(1L), 436),
				new Ingredient(147L, "요거트", findCategoryById(12L), findUnitById(20L), 182),
				new Ingredient(148L, "요구르트", findCategoryById(12L), findUnitById(3L), 0),
				new Ingredient(149L, "요리당", findCategoryById(10L), findUnitById(1L), 69),
				new Ingredient(150L, "우메보시", findCategoryById(10L), findUnitById(5L), 437),
				new Ingredient(151L, "중력분", findCategoryById(4L), findUnitById(3L), 1),
				new Ingredient(152L, "쫄면", findCategoryById(9L), findUnitById(3L), 5),
				new Ingredient(153L, "참기름", findCategoryById(10L), findUnitById(1L), 51),
				new Ingredient(154L, "찹쌀", findCategoryById(2L), findUnitById(11L), 796),
				new Ingredient(155L, "청고추", findCategoryById(1L), findUnitById(5L), 210),
				new Ingredient(156L, "체다치즈", findCategoryById(12L), findUnitById(18L), 26),
				new Ingredient(157L, "초콜릿", findCategoryById(9L), findUnitById(3L), 1),
				new Ingredient(158L, "춘장", findCategoryById(10L), findUnitById(1L), 25),
				new Ingredient(159L, "치즈", findCategoryById(12L), findUnitById(18L), 34),
				new Ingredient(160L, "치커리", findCategoryById(1L), findUnitById(18L), 140),
				new Ingredient(161L, "카레", findCategoryById(10L), findUnitById(17L), 238),
				new Ingredient(162L, "케찹", findCategoryById(10L), findUnitById(1L), 270),
				new Ingredient(163L, "코다리", findCategoryById(8L), findUnitById(19L), 4350),
				new Ingredient(164L, "콩나물", findCategoryById(1L), findUnitById(9L), 213),
				new Ingredient(165L, "크림치즈", findCategoryById(12L), findUnitById(3L), 4),
				new Ingredient(166L, "토마토", findCategoryById(1L), findUnitById(5L), 596),
				new Ingredient(167L, "토마토페이스트", findCategoryById(10L), findUnitById(1L), 69),
				new Ingredient(168L, "통마늘", findCategoryById(1L), findUnitById(5L), 179),
				new Ingredient(169L, "튀김가루", findCategoryById(4L), findUnitById(1L), 41),
				new Ingredient(170L, "파스타면", findCategoryById(4L), findUnitById(3L), 2),
				new Ingredient(171L, "파스타소스", findCategoryById(10L), findUnitById(11L), 8190),
				new Ingredient(172L, "파슬리", findCategoryById(1L), findUnitById(3L), 13),
				new Ingredient(173L, "팔각", findCategoryById(10L), findUnitById(5L), 58),
				new Ingredient(174L, "팥", findCategoryById(7L), findUnitById(3L), 9),
				new Ingredient(175L, "포도씨유", findCategoryById(10L), findUnitById(1L), 238),
				new Ingredient(176L, "풋마늘", findCategoryById(1L), findUnitById(5L), 45),
				new Ingredient(177L, "프룬", findCategoryById(13L), findUnitById(5L), 123),
				new Ingredient(178L, "피스타치오", findCategoryById(6L), findUnitById(3L), 1),
				new Ingredient(179L, "피칸", findCategoryById(6L), findUnitById(3L), 3),
				new Ingredient(180L, "피클", findCategoryById(9L), findUnitById(3L), 2),
				new Ingredient(181L, "핫소스", findCategoryById(10L), findUnitById(1L), 808),
				new Ingredient(182L, "허브솔트", findCategoryById(10L), findUnitById(1L), 387),
				new Ingredient(183L, "헤이즐넛가루", findCategoryById(6L), findUnitById(3L), 24),
				new Ingredient(184L, "현미", findCategoryById(7L), findUnitById(11L), 746),
				new Ingredient(185L, "호두", findCategoryById(6L), findUnitById(3L), 1),
				new Ingredient(186L, "홍고추", findCategoryById(1L), findUnitById(5L), 122),
				new Ingredient(187L, "황설탕", findCategoryById(10L), findUnitById(1L), 88),
				new Ingredient(188L, "훈제연어", findCategoryById(8L), findUnitById(14L), 24230),
				new Ingredient(189L, "흑미가루", findCategoryById(7L), findUnitById(3L), 14),
				new Ingredient(190L, "BP", findCategoryById(9L), findUnitById(3L), 26),
				new Ingredient(191L, "계피", findCategoryById(10L), findUnitById(1L), 345),
				new Ingredient(192L, "깨소금", findCategoryById(10L), findUnitById(1L), 570),
				new Ingredient(193L, "녹차가루", findCategoryById(10L), findUnitById(1L), 37),
				new Ingredient(194L, "느타리버섯", findCategoryById(1L), findUnitById(9L), 272),
				new Ingredient(195L, "떡", findCategoryById(9L), findUnitById(5L), 43),
				new Ingredient(196L, "럼주", findCategoryById(9L), findUnitById(1L), 69),
				new Ingredient(197L, "로메인", findCategoryById(1L), findUnitById(18L), 66),
				new Ingredient(198L, "롤빵", findCategoryById(9L), findUnitById(5L), 4600),
				new Ingredient(199L, "마늘가루", findCategoryById(10L), findUnitById(1L), 26),
				new Ingredient(200L, "마늘쫑", findCategoryById(1L), findUnitById(3L), 8),
				new Ingredient(201L, "머스타드", findCategoryById(9L), findUnitById(1L), 142),
				new Ingredient(202L, "메추리알", findCategoryById(12L), findUnitById(5L), 140),
				new Ingredient(203L, "명란젓", findCategoryById(8L), findUnitById(1L), 31),
				new Ingredient(204L, "무", findCategoryById(1L), findUnitById(9L), 223),
				new Ingredient(205L, "묵은지", findCategoryById(9L), findUnitById(16L), 643),
				new Ingredient(206L, "미나리", findCategoryById(1L), findUnitById(9L), 1070),
				new Ingredient(207L, "미림", findCategoryById(9L), findUnitById(1L), 5),
				new Ingredient(208L, "바닐라액", findCategoryById(9L), findUnitById(1L), 174),
				new Ingredient(209L, "밥이랑", findCategoryById(9L), findUnitById(5L), 145),
				new Ingredient(210L, "베이글", findCategoryById(9L), findUnitById(5L), 428),
				new Ingredient(211L, "짜장분말", findCategoryById(9L), findUnitById(17L), 890),
				new Ingredient(212L, "비엔나", findCategoryById(9L), findUnitById(3L), 2),
				new Ingredient(213L, "살사소스", findCategoryById(9L), findUnitById(1L), 221),
				new Ingredient(214L, "새우젓", findCategoryById(8L), findUnitById(1L), 18),
				new Ingredient(215L, "생강", findCategoryById(10L), findUnitById(1L), 202),
				new Ingredient(216L, "숙주", findCategoryById(1L), findUnitById(9L), 104),
				new Ingredient(217L, "순두부", findCategoryById(9L), findUnitById(17L), 1774),
				new Ingredient(218L, "슬라이스햄", findCategoryById(9L), findUnitById(18L), 110),
				new Ingredient(219L, "시금치", findCategoryById(1L), findUnitById(9L), 1995),
				new Ingredient(220L, "쌀", findCategoryById(2L), findUnitById(11L), 578),
				new Ingredient(221L, "겨자", findCategoryById(10L), findUnitById(1L), 25),
				new Ingredient(222L, "아가베시럽", findCategoryById(9L), findUnitById(1L), 340),
				new Ingredient(223L, "애느타리버섯", findCategoryById(1L), findUnitById(17L), 710),
				new Ingredient(224L, "양송이버섯", findCategoryById(1L), findUnitById(5L), 523),
				new Ingredient(225L, "엔초비", findCategoryById(8L), findUnitById(19L), 1170),
				new Ingredient(226L, "오징어몸통", findCategoryById(8L), findUnitById(5L), 2510),
				new Ingredient(227L, "오징어젓갈", findCategoryById(8L), findUnitById(1L), 41),
				new Ingredient(228L, "오트밀", findCategoryById(7L), findUnitById(3L), 11),
				new Ingredient(229L, "옥수수전분", findCategoryById(9L), findUnitById(3L), 6),
				new Ingredient(230L, "완두콩캔", findCategoryById(9L), findUnitById(3L), 0),
				new Ingredient(231L, "우동면", findCategoryById(9L), findUnitById(17L), 866),
				new Ingredient(232L, "우스터소스", findCategoryById(9L), findUnitById(1L), 75),
				new Ingredient(233L, "핫케이크가루", findCategoryById(4L), findUnitById(3L), 14),
				new Ingredient(234L, "유부", findCategoryById(9L), findUnitById(17L), 1596),
				new Ingredient(235L, "이스트", findCategoryById(9L), findUnitById(3L), 36),
				new Ingredient(236L, "잣", findCategoryById(6L), findUnitById(1L), 188),
				new Ingredient(237L, "전분", findCategoryById(9L), findUnitById(1L), 64),
				new Ingredient(238L, "찐고구마", findCategoryById(1L), findUnitById(5L), 368),
				new Ingredient(239L, "카스테라", findCategoryById(9L), findUnitById(5L), 1012),
				new Ingredient(240L, "콩잎", findCategoryById(1L), findUnitById(3L), 50),
				new Ingredient(241L, "크로와상", findCategoryById(9L), findUnitById(5L), 342),
				new Ingredient(242L, "탈지분유", findCategoryById(12L), findUnitById(3L), 1),
				new Ingredient(243L, "파마산치즈", findCategoryById(12L), findUnitById(1L), 49),
				new Ingredient(244L, "팥앙금", findCategoryById(9L), findUnitById(11L), 196),
				new Ingredient(245L, "푸실리", findCategoryById(9L), findUnitById(3L), 4),
				new Ingredient(246L, "풋고추", findCategoryById(1L), findUnitById(5L), 360),
				new Ingredient(247L, "해물", findCategoryById(8L), findUnitById(9L), 54),
				new Ingredient(248L, "햄버거빵", findCategoryById(9L), findUnitById(5L), 214),
				new Ingredient(249L, "황태포", findCategoryById(5L), findUnitById(3L), 62),
		};
		// DB 저장
		for (Ingredient ingredient : ingredients) {
			ingredientRepository.save(ingredient);
		}
	}

}
